deployment_project/deployment_project/urls.py
from django.contrib import admin
from django.urls import path, include
from test_app.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", include("test_app.urls")),
    path("", include("user_app.urls")),
    path("home/", home_view, name="home"),
]

deployment_project/test_app/urls.py
from django.urls import path
from .views import home_view

app_name = "test_app"

urlpatterns = [

    path("", home_view, name="home"),
]

deployment_project/user_app/urls.py
from django.urls import path, reverse
from .views import signup_view, profile_view, logout_view
from django.contrib.auth import views as auth_views

app_name = "user_app"

urlpatterns = [
    path("users/yourprofile/", profile_view, name="profile"),
    path("login/", auth_views.LoginView.as_view(template_name="user_app/login.html"), name="login"),
    path("signup", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),

]

deployment_project/notification_app/models.py
from django.db import models

# Create your models here.

deployment_project/user_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

deployment_project/user_app/forms.py
from django.contrib.auth.models import User 
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

class User_form(UserCreationForm):

	class Meta:

		model = User 
		fields = ["username", "password1", "password2", "email",
					"first_name", "last_name"]

deployment_project/notification_app/views.py
from django.shortcuts import render

# Create your views here.

deployment_project/test_app/views.py
from django.shortcuts import render

# Create your views here.


def home_view(request):

    return render(request, "test_app/index.html", {})

deployment_project/user_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .forms import User_form
from django.http import HttpResponseRedirect

# Create your views here.




def signup_view(request):

    form = User_form()

    if request.method == "POST":
        form = User_form(request.POST)

        if form.is_valid():

            form.save()
            
            return HttpResponseRedirect("users/login")

        return render(request, "user_app/signup.html", {"form":form})

    return render(request, "user_app/signup.html", {"form": form})



def profile_view(request):

    obj = User.objects.get(username=request.user.username)

    return render(request, "user_app/profile.html", {"person":obj})

def logout_view(request):

    return render(request, "user_app/logout.html", {})

deployment_project/test_app/templates/test_app/home.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        {{ request.user }}

    </body>
</html>

deployment_project/test_app/templates/test_app/index.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        {{ request.user }}

    </body>
</html>

deployment_project/user_app/templates/user_app/login.html
<!DOCTYPE html>
<html>
{% block content %}

<head>
	<link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300&display=swap" rel="stylesheet">

</head>
<body>
	<div class="page-content">
		<div class="block-one"></div>
		<div class="login-wrap block-two">
			<h3>RHYDO</h3>
			<h2>Login Here</h2>

			<div class="login-html">
				<div class="login-form">
					<div class="sign-in-htm">
						<form method="POST">
							{% csrf_token %}
							<div class="fieldWrapper group">
								{{ form.username.errors }}
								<div class="form_field">
									<div><small><label for="{{ form.name.id_for_label }}" class="label label-username"> Username </label></small></div>
									{{ form.username }}
								</div>
							</div>
							<div class="fieldWrapper">
								{{ form.password.errors }}
								<div class="form_field">
									<div>
										<small><label for="{{ form.name.id_for_label }}" class="label label-password"> Password  </label></small>
									</div>
									{{ form.password }}
								</div>
							</div>
							
							<div class="group">
								<input type="submit" class="button" value="SIGN IN">
							</div>
							<div class="hr"></div>
							<div class="foot-lnk">
								<span>
									<a class="signup-link" href="{% url 'user_app:signup' %}">Sign up</a>
								</span>

							</div>
						</form>
					</div>
					
				</div>
			</div>
		</div>
		<div class="block-three"></div>
	</div>
<style>
	.page-content{
		display:grid;
		grid-template-columns: 1fr 1fr 1fr;
		font-family: "Prompt", sans-serif;
		font-size: 14px;

	}

	.login-wrap{
		text-align: center;
		margin-top: 50px;
	}

	#id_username, #id_password{
		border-width:0px;
		border:none;
		border-bottom: 2px solid #696969;
		background-color: #D3D3D3;
		width: 350px;
		margin-left: -50px;
		outline: none !important;

	}
	input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
	-webkit-box-shadow: 0 0 0 30px #D3D3D3 inset !important;
	border-color: #D3D3D3;
	outline: none !important;



}


.form_field{
	background-color: #D3D3D3;
	padding-left: 50px;
	text-align: left;
	margin-bottom: 20px;
	width: 300px;
	margin-left: 25px;
}

.group{
	margin-top: 20px;
}

.label{
	margin-left: -50px;
}

h3{
	text-align:center;
}

.button{
	border: none;
	width: 350px;
	height: 50px;
	transform: matrix(1, 0, 0, 1, 0, 0);
	transition: all 0.4s ease-in-out 0s;
	box-sizing: border-box;
	background-color: black;
	font-family: 'Prompt', sans-serif;
	font-size: 14px;
	letter-spacing: 0.200006px;
	text-align: center;
	color: #ffffff;
	cursor: pointer;
	border-radius: 5px;

}

.forgot-password{
	margin-left: -50px;
	text-decoration: none;
	color: black;
}

.signup-link{
	margin-left: 10px;
	margin-right: -30px;
	text-decoration: none;
	color: black;
}
.signup-link:hover{

	color: black;
}
.forgot-password:hover{
	color: black;
	border-bottom: black 0.125em solid;
}
.signup-link:hover{
	color: black;
	border-bottom: black 0.125em solid;
}

</style>
</body>
</html>
{% endblock %}

deployment_project/user_app/templates/user_app/logout.html
{% block content %}
	<p> Vous etes deconnecte</p>

{% endblock %}

deployment_project/user_app/templates/user_app/profile.html
{% block content%}
	
<div class="informations-user">
    <p>
        <label>Username:</label>

        {{person.username}}
    </p>
    <p>
        {{person.email}}
    </p>
</div>


<style>
    .profile-image{
        height: 50px;
        width: 50px;
        margin-left: 50px;
        margin-top: 40px;
    }
    .informations-user{
        margin-left: 100px;
    }
    .change-password-profile{
        margin-left: 280px;
        margin-top: 20px;
    }
    .change-profile-photo{
        margin-top: 20px;
        margin-left: 100px;
    }
    .fieldWrapper{
        margin-left: 100px;
    }



    .content-link{
font-family: 'Roboto', sans-serif;
font-size: 14px;
text-decoration: none;
color: black;
}


.content-link:hover{
color: black;
border-bottom: black 0.125em solid;
}

</style>


{% endblock %}

deployment_project/user_app/templates/user_app/signup.html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300&display=swap" rel="stylesheet">

  </head>
<body>
 
{% block content %}
  	
  <form method="POST" class="registration_form">
    <h2 class="name-brand">Rhydo</h2>
    <h3 class="title-page">Sign up page </h3>
    {% csrf_token %}
    
  <div class="allField">
    <div class="fieldWrapper">
      {{ form.username.errors }}
      <p class="label_form"><label for="{{ form.username.id_for_label }}">Username </label></p>
      <div class="form_field">{{ form.username }}</div>
  </div>
  <div class="fieldWrapper">
    {{ form.first_name.errors }}
    <p class="label_form"><label for="{{ form.first_name.id_for_label }}">First name </label></p>
    <div class="form_field">{{ form.first_name }}</div>
  </div>
  <div class="fieldWrapper">
    {{ form.last_name.errors }}
    <p class="label_form"><label for="{{ form.last_name.id_for_label }}">Last name </label></p>
    <div class="form_field">{{ form.last_name }}</div>
  </div>
  <div class="fieldWrapper">
    {{ form.email.errors }}
    <p class="label_form"><label for="{{ form.email.id_for_label }}">Email </label></p>
    <div class="form_field">{{ form.email }}</div>
  </div>
  <div class="fieldWrapper">
    {{ form.password1.errors }}
    <p class="label_form"><label for="{{ form.password1.id_for_label }}">password </label></p>
    <div class="form_field">{{ form.password1 }}</div>
</div>
<div class="fieldWrapper">
  {{ form.password2.errors }}
  <p class="label_form"><label for="{{ form.password2.id_for_label }}">Confirm password </label></p>
  <div class="form_field">{{ form.password2 }}</div>
</div>


</div>
      
  <input type="submit" value="Sign in" class="signin">
  <div class="login-link-container">
    <a href="{% url 'user_app:login' %}" class="login-link">Already an Account?</a>
  </div>
</form>

<style>
  .registration_form{
    font-family: 'Prompt', sans-serif;
    font-size: 14px;
    margin-left: 400px;
    margin-top: 100px;
  }
  .label_form{
    margin-bottom: 0px;
  }
  #id_username, #id_password1, #id_password2, #id_email, #id_first_name, #id_last_name{
    width: 345px;
  }

input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
	-webkit-box-shadow: 0 0 0 30px #D3D3D3 inset !important;
	border-color: #D3D3D3;
	outline: none !important;
}

 .title-page{
    margin-left: 120px;
}
.name-brand{
  margin-left: 140px;
}

.signin{
  margin-top: 20px;
  border: none;
	width: 350px;
	height: 50px;
	transform: matrix(1, 0, 0, 1, 0, 0);
	transition: all 0.4s ease-in-out 0s;
	box-sizing: border-box;
	background-color: black;
	font-family: 'Prompt', sans-serif;
	font-size: 14px;
	letter-spacing: 0.200006px;
	text-align: center;
	color: #ffffff;
	cursor: pointer;
	border-radius: 5px;
}

.login-link{
	margin-left: 10px;
	text-decoration: none;
	color: black;
}
.login-link:hover{
	color: black;
	border-bottom: black 0.125em solid;
}
.login-link-container{
  margin-left: 100px;
  margin-top: 10px;
}
</style>
{% endblock %}

 
</body>
</html>